# Generated by Django 5.0.6 on 2024-05-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_profile',
            field=models.ImageField(blank=True, default='static/picture_profile/base.jpg', upload_to='users/users_picture_profile'),
        ),
    ]
