# Generated by Django 5.0.6 on 2024-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20240524_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', through='custom_user.UserAchievementStatus', to='custom_user.userachievement'),
        ),
    ]
