# Generated by Django 5.0.6 on 2024-05-28 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventGuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128)),
                ('event_descr', models.CharField(blank=True, max_length=256, null=True)),
                ('event_address', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField()),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_main_photo', models.ImageField(upload_to='users/events')),
                ('additional_event_photo', models.ImageField(blank=True, null=True, upload_to='users/events')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('guests', models.ManyToManyField(related_name='user_events', through='events.EventGuests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventtypes')),
            ],
        ),
        migrations.AddField(
            model_name='eventguests',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
    ]
