# Generated by Django 5.0.6 on 2024-05-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtypes',
            old_name='event_name',
            new_name='event_type',
        ),
    ]
