# Generated by Django 5.0.6 on 2024-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_name_eventtypes_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='additional_event_photo',
            field=models.ImageField(blank=True, upload_to='users/events'),
        ),
    ]
