# Generated by Django 5.0.6 on 2024-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_additional_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_main_photo',
            field=models.ImageField(blank=True, upload_to='users/events'),
        ),
    ]
